# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "fdt"
edition = "2021"

[features]
default = []
std = []

[dependencies]
zerocopy.workspace = true
zerocopy_helpers.workspace = true

[lints]
workspace = true
