# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "hyperv_ic_resources"
edition = "2021"

[dependencies]
mesh.workspace = true
vm_resource.workspace = true

[lints]
workspace = true
