name: Validate and associate VSO work items 
inputs:
  # Secrets
  # These secrets describe the HvLite-GitHub service principal and associated Azure subscription,
  # which, along with the GITHUB_TOKEN, are used to authenticate GitHub Actions to Azure with OpenID Connect.
  # The service principal has federated identity credentials configured describing which branches and 
  # scenarios can be authenticated.
  OPENVMM_CLIENT_ID:
    required: true
    description: "HvLite-Github service principal client id"
  OPENVMM_TENANT_ID:
    required: true
    description: "HvLite-Github service principal tenant id"
  OPENVMM_SUBSCRIPTION_ID:
    required: true
    description: "HvLite subscription id"

runs:
  using: "composite"
  steps:
    - uses: Azure/login@v1
      with:
        client-id: ${{ inputs.OPENVMM_CLIENT_ID }}
        tenant-id: ${{ inputs.OPENVMM_TENANT_ID }}
        subscription-id: ${{ inputs.OPENVMM_SUBSCRIPTION_ID }}

    - name: Pull Azure Key Vault secrets
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "HvLite-PATs"
        secrets: 'VsoWorkItemPAT'  # comma separated list of secret keys that need to be fetched from the Key Vault
      id: AzureKeyVault # Reference the secrets with steps.AzureKeyVault.outputs.mySecret1

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.0'

    - name: Process associated work items
      env:
        BODY: ${{ github.event.pull_request.body }}
      run: |
        pip install -r .github/scripts/requirements.txt

        flags=''
        if [ "${{ github.event.pull_request.merged }}" != 'true' ]; then
            flags='--validate-only'
        fi

        echo -n "$BODY" | python .github/scripts/work-item.py "${{ steps.AzureKeyVault.outputs.VsoWorkItemPAT }}" "https://github.com/microsoft/HvLite/pull/${{ github.event.number }}" $flags

      shell: bash
