# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "cvm_tracing"
edition = "2021"

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
