# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "nvme_common"
edition = "2021"

[dependencies]
disk_backend.workspace = true
nvme_spec.workspace = true

thiserror.workspace = true

[lints]
workspace = true
