# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "chipset_device"
edition = "2021"

[dependencies]
mesh.workspace = true
inspect.workspace = true

[lints]
workspace = true
