# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "tdcall"
edition = "2021"

[features]
default = []
std = []
tracing = ["std", "dep:tracing"]

[dependencies]
hvdef.workspace = true
memory_range.workspace = true
x86defs.workspace = true

tracing = { workspace = true, optional = true }

[lints]
workspace = true
