# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "inspect_rlimit"
edition = "2021"

[target.'cfg(unix)'.dependencies]
inspect = { workspace = true, features = ["std"] }

cfg-if.workspace = true
libc.workspace = true
thiserror.workspace = true

[lints]
workspace = true
