# Because specifying non-default pull_request triggers causes the check to not
# be a required check for PRs and because `closed` is not in the default pull_request
# triggers, we need a separate workflow for the closed event.
#
# Please ensure the logic of this file matches work-item-closed.yml
name: Work Item Check
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, edited, opened, reopened, closed]

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  id-token: write
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
  

jobs:
  WorkItems:
    runs-on: windows-latest
    if: github.event_name == 'pull_request' && (github.event.pull_request.merged == true || github.event.action != 'closed')
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4

      - name: Validate work items
        uses: ./.github/actions/workitems
        with:
          OPENVMM_CLIENT_ID: ${{ secrets.OPENVMM_CLIENT_ID }}
          OPENVMM_TENANT_ID: ${{ secrets.OPENVMM_TENANT_ID }}
          OPENVMM_SUBSCRIPTION_ID:  ${{ secrets.OPENVMM_SUBSCRIPTION_ID }}
